import { expect, it, vi } from 'vitest'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { TalentModel, decodeLoadout, encodeLoadout } from './talents'
import type { TalentLayout, TalentTree } from './types'
import { visibleTalentEdges, withTalentLayout } from './talent-layout'
import { parseAddonExport } from '../import/character'
import { artifactGate } from '../../../tests/artifact-gate.js'

// Talent trees are generated by `npm run catalog:build` and gitignored; only each catalog's
// manifest.json is tracked, so the directory exists on a clean clone but the trees do not.
const dir = existsSync('public/catalogs')
  ? readdirSync('public/catalogs').find(name => name.startsWith('12.1.0.69814-') && !name.includes(' '))
  : undefined
const treeGate = (classId: number) =>
  artifactGate(`public/catalogs/${dir}/talents/class-${classId}.json`, 'npm run catalog:build')
const evokerGate = treeGate(9)
const demonHunterGate = treeGate(12)

it.skipIf(evokerGate)('loads the selected engine layout and keeps pinned rules after live descriptions expire' + evokerGate, async () => {
  const manifest = JSON.parse(readFileSync('public/engine/manifest.json', 'utf8'))
  const tree = JSON.parse(readFileSync(`public/catalogs/${dir}/talents/class-9.json`, 'utf8')) as TalentTree
  const layout = JSON.parse(readFileSync('public/talent-layout/class-9.json', 'utf8')) as TalentLayout
  const commit = '1'.repeat(40)
  manifest.engine.upstreamCommit = commit
  const fetchLayout = vi.fn(async () => new Response(JSON.stringify({ ...layout, engineCommit: commit, expiresAt: '2000-01-01T00:00:00Z' })))
  vi.stubGlobal('fetch', fetchLayout)
  try {
    const loaded = await withTalentLayout(tree, { ok: true, artifact: 'fallback', engineDir: '/engine/versions/layout-check/fallback/',
      maxThreads: 1, profilesets: false, manifest })
    expect(fetchLayout).toHaveBeenCalledWith('/engine/versions/layout-check/talent-layout/class-9.json')
    expect(loaded.layout?.descriptions).toEqual({})
    expect(loaded.layout?.edges).toEqual(layout.edges)
    expect(loaded.layout?.budgetSources).toEqual(layout.budgetSources)
    await expect(withTalentLayout(tree, { ok: true, artifact: 'threaded', engineDir: '/engine/versions/wrong-layout/',
      maxThreads: 16, profilesets: true, manifest: { ...manifest, engine: { ...manifest.engine, upstreamCommit: '2'.repeat(40) } } })).rejects.toThrow('refreshed')
  } finally { vi.unstubAllGlobals() }
})

it.skipIf(demonHunterGate)('renders the reported Vengeance loadout with unique connections and unchanged talent encoding' + demonHunterGate, () => {
  const tree = JSON.parse(readFileSync(`public/catalogs/${dir}/talents/class-12.json`, 'utf8')) as TalentTree
  tree.layout = JSON.parse(readFileSync('public/talent-layout/class-12.json', 'utf8')) as TalentLayout
  const character = parseAddonExport(readFileSync('tests/fixtures/addon-export-vengeance-import.simc', 'utf8'))
  const model = new TalentModel(tree, 581, 90)
  const placeholders = model.nodes.filter(n => n.maxRanks === 0)
  expect(placeholders.length).toBeGreaterThan(0)
  expect(model.visibleNodes().every(n => n.maxRanks > 0)).toBe(true)
  expect(placeholders.every(n => model.node(n.nodeId) !== null)).toBe(true)
  const text = character.loadouts[0].talents
  const decoded = decodeLoadout(model, text)
  expect(decoded.errors).toEqual([])
  const active = decodeLoadout(model, character.talents!).selection!
  expect(model.validate(active).issues).toEqual([])
  expect(model.validate(active).spent).toEqual({ class: 34, spec: 34, hero: 13 })
  const freeHero = active.picks.find(p => model.node(p.nodeId)?.subTreeId === model.validate(active).activeSubTreeId && model.isGranted(model.node(p.nodeId)!.entries.find(e => e.entryId === p.entryId)!))!
  expect(freeHero).toBeDefined()
  expect(model.allocate(active, freeHero.nodeId, freeHero.entryId, -1).refused).toContain('granted')
  const ids = new Set(model.visibleNodes().map(n => n.nodeId))
  const raw = tree.layout.edges.filter(e => e.visual && ids.has(e.from) && ids.has(e.to))
  const lines = visibleTalentEdges(tree.layout, ids)
  expect(lines.length).toBeLessThan(raw.length)
  expect(new Set(lines.map(e => `${e.from}:${e.to}`)).size).toBe(lines.length)
  expect(decodeLoadout(model, encodeLoadout(model, decoded.selection!)).selection).toEqual(decoded.selection)
})

it('draws repeated client-table connections once across every class without changing rule edges', () => {
  let repeated = 0
  for (const file of readdirSync('public/talent-layout')) {
    const layout = JSON.parse(readFileSync(`public/talent-layout/${file}`, 'utf8')) as TalentLayout
    const before = JSON.stringify(layout.edges)
    const visible = new Set(Object.keys(layout.nodes).map(Number))
    const lines = visibleTalentEdges(layout, visible)
    const keys = layout.edges.filter(e => e.visual && visible.has(e.from) && visible.has(e.to)).map(e => `${e.from}:${e.to}`)
    repeated += keys.length - new Set(keys).size
    expect(lines.map(e => `${e.from}:${e.to}`)).toEqual([...new Set(keys)])
    expect(JSON.stringify(layout.edges)).toBe(before)
    expect(visibleTalentEdges(layout, new Set())).toEqual([])
  }
  expect(repeated).toBeGreaterThan(0)
})

it.skipIf(evokerGate)('uses versioned coordinates and budgets without changing the imported build codec' + evokerGate, () => {
  const tree = JSON.parse(readFileSync('public/catalogs/' + dir + '/talents/class-9.json', 'utf8')) as TalentTree
  tree.layout = JSON.parse(readFileSync('public/talent-layout/class-9.json', 'utf8')) as TalentLayout
  const model = new TalentModel(tree, 266, 90)
  const text = readFileSync('tests/fixtures/addon-export-demonology.simc', 'utf8').match(/^talents=(.+)$/m)![1]
  const decoded = decodeLoadout(model, text)
  expect(decoded.errors).toEqual([])
  expect(decodeLoadout(model, encodeLoadout(model, decoded.selection!)).selection).toEqual(decoded.selection)
  expect(model.pointBudget()).toEqual({ class: 34, spec: 34, hero: 13 })
  expect(model.validate(decoded.selection!).issues).toEqual([])
  const omittedGrants = { ...decoded.selection!, picks: decoded.selection!.picks.filter(pick => !model.isGranted(model.node(pick.nodeId)!.entries.find(entry => entry.entryId === pick.entryId)!)) }
  expect(model.validate(omittedGrants).issues).toEqual([])
  expect(model.nodeStatus(omittedGrants).filter(node => node.granted).every(node => node.rank >= 1)).toBe(true)
  const parent = decoded.selection!.picks.find(pick => tree.layout!.edges.some(edge => edge.from === pick.nodeId) && !model.nodeStatus(decoded.selection!).find(row => row.nodeId === pick.nodeId)?.granted)!
  const refunded = model.allocate(decoded.selection!, parent.nodeId, parent.entryId, -1)
  expect(refunded.refused).toBeNull()
  expect(model.validate(refunded.selection).issues).toEqual([])
  expect(refunded.selection.picks.length).toBeLessThan(decoded.selection!.picks.length)
  const selector = model.visibleNodes().find(node => node.treeIndex === 4)!
  const selected = decoded.selection!.picks.find(pick => pick.nodeId === selector.nodeId)!
  const other = selector.entries.find(entry => entry.entryId !== selected.entryId)!
  const switched = model.allocate(decoded.selection!, selector.nodeId, other.entryId, 1)
  expect(switched.refused).toBeNull()
  expect(model.validate(switched.selection).spent.hero).toBe(0)
  const available = model.nodeStatus(switched.selection).find(row => row.available && row.rank === 0 && model.node(row.nodeId)?.treeIndex === 3)!
  expect(available).toBeDefined()
  const entry = model.node(available.nodeId)!.entries[0]
  expect(model.allocate(switched.selection, available.nodeId, entry.entryId, 1).refused).toBeNull()
})
